version: "3.7"
services:
  suricata:
    build: ./suricata
    container_name: suricata
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - suricata-data:/var/log/suricata
    environment:
      SURICATA_OPTIONS: "-i enp9s0"

  opensearch-node:
    container_name: opensearch-node
    image: opensearchproject/opensearch:2.3.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        #- compatibility.override_main_response_version=true
        #- DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - ids-network
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    networks:
      - ids-network
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]' # must be a string with no spaces when specified as an environment variable

  logstash:
    build: ./logstash
    container_name: logstash
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      - suricata-data:/var/log/suricata
    networks:
      - ids-network
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

volumes:
  opensearch-data:
  suricata-data:

networks:
  ids-network:
